### ISSUE TITLE
Updated Migration: Does not load new changes 

### ISSUE THREAD

**Issue by numaanjaved** [beyondcode/laravel-er-diagram-generator#107]
I have made changes to a migration and removed a foreign key from it, updated its model and all 

but when I generate its erd, the removed foreign key is still there in the model. 

I tried optimizing, but it did not change anything. 

Any help would be appreciated, thank s

**Comment by mechelon** [comment]
The Generator checks for the relations defined inside the `Model`, not in the database, so I could not reproduce this bug.
If you can provide a more detailed description, feel free to reopen.
