### ISSUE TITLE
Recursive path + class exclusions

### ISSUE THREAD

**Issue by vpratfr** [beyondcode/laravel-er-diagram-generator#12]
It would be convenient to be able to specify a single model directory and have it traversed recursively. 

In our app, we have 5 subdirectories and adding one to the configuration can easily get missed.

One way to implement that, and stay backwards compatible with current configs could be to specify the folders as key/values. 

E.g. 

```
[
  app_path('Models') => [
    'recursive' => true, // key/value to pass settings
  ],
  app_path('Models'), // no key means just use default options for that folder
]
```

**Comment by mpociot** [comment]
This is now implemented in 1.1.0
