### ISSUE TITLE
Exception for sh1 dot not found

### ISSUE THREAD

**Issue by vmeijer** [beyondcode/laravel-er-diagram-generator#13]
Hello, and first of all thank you for creating such a great package. I am looking forward to use it in our team for thorough documentation.

However, I am encountering an Exception and I am not sure which way to go now. Could you take a look with me and point me in the right direction please?

The command I use is `php artisan generate:erd` and the output is:  
![dot not found](https://user-images.githubusercontent.com/11903368/42494377-6946f9cc-8420-11e8-886a-7345e5d0c91f.png)

I see that it might have to do with 'dot' in https://github.com/phpDocumentor/GraphViz/blob/master/src/phpDocumentor/GraphViz/Graph.php#L336  

----
Other information that might be useful:

I use the standard erd-generator.php config that was copied during the installation.  
In this config file I only changed the content of the array 'directories':
```php
    'directories' => [
         app_path('Models'),
         app_path('Models/*'),
         app_path('Models/*/*'),
    ],
```

The library 'laravel/framework' in use is version 5.6.16  

In composer.json this entry was added in the 'require-dev' section:  
`"beyondcode/laravel-er-diagram-generator": "^0.2.2"`  

In composer.lock the following packages were automatically installed together with yours:   
* doctrine/annotations version 1.6.0  
* doctrine/cache version 1.7.1  
* doctrine/collections version 1.5.0  
* doctrine/common version 2.8.1  
* doctrine/dbal version 2.7.1  
* phpdocumentor/graphviz version 1.0.4  

Operating System: Linux/Ubuntu 16.04

**Comment by simderoemer** [comment]
I had that issue yesterday, I'm on mac, I had to update xcode.
xcode-select --install
Then install "brew install graphviz" again

I hope that helps,

S

**Comment by mpociot** [comment]
Yeah, it looks like you do not have `graphviz` / `dot` installed properly. Please try updating graphviz.

```
brew upgrade graphviz
```

**Comment by vmeijer** [comment]
Thank you both so much! I work on Linux/Ubuntu and I used `sudo apt-get install graphviz`. Works like expected now :+1:
