### ISSUE TITLE
An error occurred while creating the graph; GraphViz returned: The command "dot" wrong or could not be found

### ISSUE THREAD

**Issue by 28development** [beyondcode/laravel-er-diagram-generator#14]
Hi,

how can I install the graph lib on windows, brew only works on mac

**Comment by mpociot** [comment]
Hi,

sorry - I do not know. I would suggest that you install graphviz inside of Homestead using `apt-get install graphpviz` and generate the image there.

**Comment by jorostoyanov** [comment]
Just a quick note for those experiencing the same issue.

The package is called `graphviz`, not `graphpviz`, so the install command should be `apt-get install graphviz` :)

**Comment by Atnaize** [comment]
FYI For installing Graphviz on windows, just download it [there](https://graphviz.gitlab.io/_pages/Download/Download_windows.html). 

Then add the bin folder to your path, by default `C:\Program Files (x86)\Graphviz2.38\bin`
