### ISSUE TITLE
Models not found if they have declare(strict_types=1)

### ISSUE THREAD

**Issue by joe-pritchard** [beyondcode/laravel-er-diagram-generator#16]
All of my models start with the strict types declaration, and when I run the generator I see Models found: 0. 

Anyone with strict types declared in only _some_ of their model classes would see those models being omitted from the diagram.

This is because the strict types declaration throws off the `ModelFinder::getFullyQualifiedClassNameFromFile` method since it looks in the first element in `$statements`, which in my case is the strict types declaration and not the body of the class. It's a simple fix, I'll submit a PR :)

**Comment by joe-pritchard** [comment]
PR here: #17

**Comment by mpociot** [comment]
Thanks for the PR! I just tagged a new release
