### ISSUE TITLE
ParserAbstract.php error

### ISSUE THREAD

**Issue by shafiramaki** [beyondcode/laravel-er-diagram-generator#22]
In ParserAbstract.php line 313:
  Syntax error, unexpected T_LIST, expecting T_STRING on line 7

**Comment by jhoff** [comment]
It seems like the ModelFinder class is parsing any file that it encounters, assuming that it is a .php file. Is there a chance that you have a non-php file in one of your directories?

This should be a pretty easy fix I would think.
