### ISSUE TITLE
Taking it more into width than height

### ISSUE THREAD

**Issue by Astinox** [beyondcode/laravel-er-diagram-generator#3]
Hey there!
First of all: Great work, it seems to work like a charme. It saves so much time when it comes to manually documenting all of that stuff.

However, due to the way it is made, it is kind of hard for bigger projects to use it. I've tried it for one of our projects which is currently in development, and you can see the clear dimensions of the size here:

http://prntscr.com/k21hem

Maybe there is a way of extending it more into the width instead of height. This would make it much more usefull when it comes to using it.

Nontheless, really great work and appreciate it!

**Comment by mpociot** [comment]
Hi,

There are multiple configuration settings that you could try here. The graph, for example, has a „rank_dir“ property which defines the direction in which the graph will expand. But it also has to do with how the lines will be drawn. 

Please play around with the graphviz settings to produce good results for your specific project.
