### ISSUE TITLE
An error occurred while creating the graph

### ISSUE THREAD

**Issue by Eugene-Melbourne** [beyondcode/laravel-er-diagram-generator#33]
phpDocumentor\GraphViz\Exception  : An error occurred while creating the graph; GraphViz returned: sh: 1: dot: not found

 Exception trace:

  1   phpDocumentor\GraphViz\Graph::export("'png'", "'output.png'")
     .../vendor/beyondcode/laravel-er-diagram-generator/src/GenerateDiagramCommand.php:77

  2   BeyondCode\ErdGenerator\GenerateDiagramCommand::handle()
      .../vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

**Comment by jhoff** [comment]
I think this means that you don't have GraphViz installed properly, IIRC.

**Comment by jhoff** [comment]
@misump You might want to open a separate issue for that. The `sh: 1: dot: not found` error occurs when GraphViz isn't installed. Your error seems different.

**Comment by urfusion** [comment]
I am getting below error on window 7, xampp7 , laravel 5.5.45

# php artisan generate:erd
Found 203 models.
Inspecting model relations.

  20/203 [==>-------------------------]   9%
  40/203 [=====>----------------------]  19%
  60/203 [========>-------------------]  29%
  80/203 [===========>----------------]  39%
 100/203 [=============>--------------]  49%
 120/203 [================>-----------]  59%
 140/203 [===================>--------]  68%
 160/203 [======================>-----]  78%
 180/203 [========================>---]  88%
 200/203 [===========================>]  98%
 203/203 [============================] 100%
In Graph.php line 375:

  An error occurred while creating the graph; GraphViz returned: 'dot' is not recognized as an internal or external c
  ommand,
  operable program or batch file.

**Comment by JohanIskandar** [comment]
From  https://graphviz.gitlab.io/_pages/Download/Download_windows.html
Note: These Visual Studio packages do not alter the PATH variable or access the registry at all. If you wish to use the command-line interface to Graphviz or are using some other program that calls a Graphviz program, you will need to set the PATH variable yourself.


Hope this helps

**Comment by jafar690** [comment]
this is an issue with GraphViz installation, not the package itself

**Comment by takifouhal** [comment]
i had the same problem (on Windows) , but when i tried with Git Bash it worked

**Comment by josh-boat365** [comment]
This worked fine for me 
`php artisan generate:erd --format=text`
This will give you a textual representation of the graph from your models `app/Models`
Then you can try and paste this into a tool like: [https://dreampuf.github.io/GraphvizOnline/](https://dreampuf.github.io/GraphvizOnline/)
