### ISSUE TITLE
Not showing relationships from packages

### ISSUE THREAD

**Issue by coding-sunshine** [beyondcode/laravel-er-diagram-generator#34]
I am using https://github.com/spatie/laravel-permission
to manage roles and permissions and my model includes the HasRole trait, but the generated er-diagram doesn't show any relation

**Comment by manoelsouzaunicef** [comment]
Hello! You were able to solve this situation ?!

**Comment by rivajunior** [comment]
Same with me

**Comment by huangxiangrongphper** [comment]
You can do this temporarily.
`config/erd-generator.php`
```
      'directories' => [
        base_path('app/Models/'),
        base_path('vendor/spatie/laravel-permission/src/Models/'),
        base_path('vendor/laravel/framework/src/Illuminate/Notifications/')
    ],
```

**Comment by coding-sunshine** [comment]
thanks for the help @huangxiangrongphper
