### ISSUE TITLE
memory_limit issue

### ISSUE THREAD

**Issue by heromiyo** [beyondcode/laravel-er-diagram-generator#35]
Found 22 models.
Inspecting model relations.
 14/22 [=================>----------]  63%PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in C:\xampp\htdocs\zedshoply\vendor\laravel\framewor
k\src\Illuminate\Database\Eloquent\Concerns\HasRelationships.php on line 656
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 8192 bytes) in C:\xampp\htdocs\zedshoply\vendor\monolog\monolog\src\Monolog\Formatter\LineFormatter.php on
 line 142

what i did:
i edited php.ini and set memory_limit to 1G 
still got error 
then i tried to edit the monolog source and added this line 
ini_set("memory_limit", -1);

still same error

**Comment by chexj** [comment]
no answer? ::>_<::
