### ISSUE TITLE
Found 0 models.

### ISSUE THREAD

**Issue by IrisDande** [beyondcode/laravel-er-diagram-generator#4]
After running command php artisan generate:erd
it say that:
"
Found 0 models.
Inspecing model relations.
Wrote diagram to graph.png
"

**Comment by nkootstra** [comment]
```
    'directories' => [
        app_path('')
        // app_path('models'),
    ],
```
Just add app_path() to directories :)

**Comment by IrisDande** [comment]
Ops!, It didn't mention in Readme file

**Comment by robsontenorio** [comment]
it works. Maybe the default install should consider this configuration:
```
 'directories' => [
        app_path('')
        // app_path('models'),
    ],
```
