### ISSUE TITLE
 There are no commands defined in the "generate" namespace.

### ISSUE THREAD

**Issue by aoamusat** [beyondcode/laravel-er-diagram-generator#45]
Whenever I run `php artisan generate:erd`, this is what I got 

>  There are no commands defined in the "generate" namespace.

>

**Comment by MoatazAbdAlmageed** [comment]
@aoamusat are you registered this 
$app->register(BeyondCode\ErdGenerator\ErdGeneratorServiceProvider::class);
 in bootstrap/app.php

**Comment by gilles6** [comment]
I get the same error. Is it compatible with `Laravel Framework 7.12.0` ?

**Comment by aoamusat** [comment]
@gilles6 Thank you
