### ISSUE TITLE
Found 0 models. because Models in separate directory

### ISSUE THREAD

**Issue by MoatazAbdAlmageed** [beyondcode/laravel-er-diagram-generator#46]
![image](https://user-images.githubusercontent.com/17373050/52063675-bd618200-257b-11e9-9d94-0004fd3fc76c.png)

**Comment by diogogomeswww** [comment]
@MoatazAbdAlmageed are you using Laravel?

If you are follow the instructions and publish the config file.
In the config file there's a directories key where you can add all the folders to be scanned:
![image](https://user-images.githubusercontent.com/11543163/55639751-00311780-57c2-11e9-8b06-0c5bfe81cb91.png)

**Comment by MoatazAbdAlmageed** [comment]
Thanks, it works
