### ISSUE TITLE
[5.8] BelongsTo relationships are not displayed on the diagram

### ISSUE THREAD

**Issue by vintagesucks** [beyondcode/laravel-er-diagram-generator#52]
`BelongsTo` relationships are not displayed on the diagram.

---

By dumping the catched `Throwable` in `RelationFinder::getRelationshipFromMethodAndModel()`, I got the following message:

```
Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::getForeignKey()
```

Offending line:
https://github.com/beyondcode/laravel-er-diagram-generator/blob/43c3a3dff8030923a66b42395294e5c7ce502797/src/RelationFinder.php#L83

---

It's probably been the case since https://github.com/laravel/framework/commit/2ee18923eaff142a89439f0adf0d3f15c30db85b changed the `BelongsTo` API:

* `Laravel 5.7`: [`getForeignKey`](https://laravel.com/api/5.7/Illuminate/Database/Eloquent/Relations/BelongsTo.html#method_getForeignKey)

* `Laravel 5.8`: [`getForeignKeyName`](https://laravel.com/api/5.8/Illuminate/Database/Eloquent/Relations/BelongsTo.html#method_getForeignKeyName)

**Comment by phillz** [comment]
Thanks Yahav, the change in the code, solve the issue.
