### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fridzema** [beyondcode/laravel-er-diagram-generator#6]
Hello, 

I have a pretty big app with a lot of models/relations. 

`php artisan generate:erd output.svg --format=svg`

i get the following error:
```php
95/95 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
   phpDocumentor\GraphViz\Exception  : An error occurred while creating the graph; GraphViz returned: Error: <stdin>: syntax error in line 35 near '\'

  at /Users/rf/workspace/pmp/vendor/phpdocumentor/graphviz/src/phpDocumentor/GraphViz/Graph.php:375
    371|         exec($this->path . "dot -T$type -o$filename < $tmpfileArg 2>&1", $output, $code);
    372|         unlink($tmpfile);
    373| 
    374|         if ($code != 0) {
  > 375|             throw new Exception(
    376|                 'An error occurred while creating the graph; GraphViz returned: '
    377|                 . implode(PHP_EOL, $output)
    378|             );
    379|         }

  Exception trace:

  1   phpDocumentor\GraphViz\Graph::export("'svg'", "'output.svg'")
      /Users/rf/workspace/pmp/vendor/beyondcode/laravel-er-diagram-generator/src/GenerateDiagramCommand.php:75

  2   BeyondCode\ErdGenerator\GenerateDiagramCommand::handle()
      /Users/rf/workspace/pmp/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29

  Please use the argument -v to see more details.
```

**Comment by mpociot** [comment]
It's hard to debug this without looking at the actual GraphViz output.
You can try to do:

```
php artisan generate:erd --format=text
```

This will give you the textual GraphViz representation.
Then you can try and paste this into a tool like: https://dreampuf.github.io/GraphvizOnline/

**Comment by fridzema** [comment]
@mpociot Thanks! 

Found the issue, typo in my code.

**Comment by Adeel-AA** [comment]
> It's hard to debug this without looking at the actual GraphViz output.
> You can try to do:
> 
> ```
> php artisan generate:erd --format=text
> ```
> 
> This will give you the textual GraphViz representation.
> Then you can try and paste this into a tool like: https://dreampuf.github.io/GraphvizOnline/



> It's hard to debug this without looking at the actual GraphViz output.
> You can try to do:
> 
> ```
> php artisan generate:erd --format=text
> ```
> 
> This will give you the textual GraphViz representation.
> Then you can try and paste this into a tool like: https://dreampuf.github.io/GraphvizOnline/

Thank you very much this helped!

**Comment by Adeel-AA** [comment]
Duplicate of #

> It's hard to debug this without looking at the actual GraphViz output.
> You can try to do:
> 
> ```
> php artisan generate:erd --format=text
> ```
> 
> This will give you the textual GraphViz representation.
> Then you can try and paste this into a tool like: https://dreampuf.github.io/GraphvizOnline/

Thank you this helped! :)

**Comment by Adeel-AA** [comment]
> It's hard to debug this without looking at the actual GraphViz output.
> You can try to do:
> 
> ```
> php artisan generate:erd --format=text
> ```
> 
> This will give you the textual GraphViz representation.
> Then you can try and paste this into a tool like: https://dreampuf.github.io/GraphvizOnline/

@mpociot Thank you this helped! :)
