### ISSUE TITLE
getAllModelsFromEachDirectory() must be of the type array

### ISSUE THREAD

**Issue by r0jx0** [beyondcode/laravel-er-diagram-generator#68]
Following the steps here (https://github.com/beyondcode/laravel-er-diagram-generator) I get the following error. I use php 7.3.6 and Laravel 6.1.0. Thank you!

![Error](https://user-images.githubusercontent.com/8269523/68546836-ec423980-03d2-11ea-8384-4f7a836746e2.JPG)

**Comment by striderwhitepderas** [comment]
It happens when the models aren't directly in the `app` directory. You need to publish the config file and modify it to point to where the models are.

**Comment by striderwhitepderas** [comment]
Same, either #65 or you need to publish the configuration and change where its looking for the models. For me I think the correct config is

```
    'directories' => [
        base_path('app/Models'),
    ],
```

I am using Laravel 6, so I am waiting for #65 to be resolved then trying from there.

**Comment by myckhel** [comment]
Solution can be found here https://stackoverflow.com/a/58797967/9241085
