### ISSUE TITLE
Default config is nowhere close to the examples shown on README

### ISSUE THREAD

**Issue by Zanark** [beyondcode/laravel-er-diagram-generator#77]
Good Evening!
I love your application and consider it a life-saver, however the default config file does not give the same output as shown on the README. Please provide us with the config file for the first output shown on the README for which we shall remain ever grateful to you.

**Comment by TripShade** [comment]
I agree in the current scenario exposing the database containing the Laravel migrations and connecting to it with a decent db editor to get the ERD was faster. Without proper config this package doesn't add any value to my workflow. The config options are somewhat explained when you follow the suggested links but its to much of a hassle to figure out how to make this work properly. In the limited scenarios if seen ERD's being used recently they seem to be mostly some after thought used only when someone new joins a project or project is passed on. This package could be of value in the sense that it auto generates while working on the project but I cant imagine someone dedicating some time in their sprint to get this package working if al they have to do to achieve the same is connect to the db.
