### ISSUE TITLE
I have installed package but it's not respond anything like error or output

### ISSUE THREAD

**Issue by punit5658** [beyondcode/laravel-er-diagram-generator#83]
![Screen Shot 2020-07-23 at 11 26 15 AM](https://user-images.githubusercontent.com/4838480/88305465-8cc55900-ccd7-11ea-98ff-fb664cae4768.png)
Here I have uploaded screenshot.

**Comment by ThaDaVos** [comment]
It may be that the package instantiates the model and if you having something inside the constructor or the boot method, it may slowdown or hang the generation - I am not sure though
