### ISSUE TITLE
Only show models in a whitelist

### ISSUE THREAD

**Issue by iforwms** [beyondcode/laravel-er-diagram-generator#86]
I have a large project with dozens of tables but I'd like to generate a graph from only a few models. 

Whilst this is possible using the `ignore` array, I would need to put in a lot of models to get the desired output. Would it be possible to add another array to the config called `whitelist` so only models in the whitelist array would be shown?

I have submitted a pull request #87 to solve this issue.

**Comment by TeNNoX** [comment]
Merged, so should be closed @iforwms
