### ISSUE TITLE
Homestead compatibility

### ISSUE THREAD

**Issue by csoutham** [beyondcode/laravel-er-diagram-generator#9]
Worth noting that Homestead doesn't come out-of-the-box with Brew (or Graphviz).
Might be worth documenting it's simply a case of running `sudo apt install linuxbrew-wrapper` and `sudo apt-get install graphviz` before running `brew install graphviz`.

**Comment by vpratfr** [comment]
Tried that and it worked nicely. Great to avoid setting it up on the local machine.

**Comment by mpociot** [comment]
I updated the README to show Homestead installation instructions.

**Comment by vpratfr** [comment]
Just to let you know: next Homestead box will already have that package installed by default (See https://github.com/laravel/homestead/issues/891). This is not yet released though.

**Comment by mpociot** [comment]
That's awesome! :)
