### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by davi5e** [beyondcode/laravel-er-diagram-generator#93]
PHP 8 compatibility isn't included in the composer.json.

**Comment by peterjaap** [comment]
Also doctrine/dbal 3.0 please :)

**Comment by lablnet** [comment]
I love to see PHP 8 compatibility

**Comment by sajendramanandhar** [comment]
php 8 version throwing error.

**Comment by penagos** [comment]
+1 to PHP 8 support.

**Comment by humanware** [comment]
php 8 and laravel 8 support please.

**Comment by penagos** [comment]
I was able to get this to work on PHP8 and Laravel 8 by ignoring composer’s language check, but native support would be nice.

**Comment by TeNNoX** [comment]
Can confirm that PR #94  works :+1: 

```json
{
    "repositories": [
        {
            "url": "https://github.com/ali-alharthi/laravel-er-diagram-generator",
            "type": "github"
        }
    ],
    "require": {
        "beyondcode/laravel-er-diagram-generator": "dev-master"
   }
}
```

**Comment by CristianH033** [comment]
Support for PHP 8 please.

**Comment by eugenevdm** [comment]
@mpociot and team, could we have some PHP 8 love here?

**Comment by MenC-Didam** [comment]
8 !!

**Comment by prasun125** [comment]
@mpociot and team,
The latest release doesn't support php version 8. I hope the following change in composer.json will help here
`"require": {
    "php": "^7.3|^8.0",
}`
Can it be added in anyway and support php version 8?

**Comment by bernhardh** [comment]
Update on this would be great!

**Comment by mohamed-okasha** [comment]
as @penagos suggest 
you can get this work by ignoring version check and -W flag

`composer require beyondcode/laravel-er-diagram-generator --dev --ignore-platform-reqs  -W`

**Comment by klimenttoshkov** [comment]
Still does not work:

> - beyondcode/laravel-er-diagram-generator 1.5.0 requires doctrine/dbal ~2.3 -> found doctrine/dbal[2.3.0-BETA1, ..., 2.13.x-dev] but it conflicts with your root composer.json require (^3.2).

**Comment by Lootfi** [comment]
Yes please <3

**Comment by Kyngo** [comment]
Seems like the devs don't care about this, they haven't said a thing.

@beyondcode please do something about this!

**Comment by sietse85** [comment]
project seems abandoned, nothing stop you from forking and making the adjustments.

**Comment by allanlaal** [comment]
which er generator shall we choose to continue this work? I vote for a separate org, with contributors from all current forks :)

this needs to live!

**Comment by azophy** [comment]
Just want to share that this PR #102 solved my problem as my repo use PHP 8. For anyone who wish to use this branch to enable `laravel-er-diagram-generator` in their codebase, this is the steps I used:

1. Edit your `composer.json` to install this package but using this PR branch as source. Please note that the comments shouldn't be actually entered into your `compose.json` as json does not actually support commenting

```
    // .. bunch of other entries ...
    // add this new `repositories` section if its not presents yet
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-er-diagram-generator"
        }
    ],
    "require-dev": {
          // insert this line into require-dev section. of course you could also insert it into regular `require` section if you prefer
        "beyondcode/laravel-er-diagram-generator": "dev-l9-compatibility",
        // ... bunch of other packages...
    },
    // .. bunch of other entries ...
```
2. run `composer update beyondcode/laravel-er-diagram-generator` to install all `laravel-er-diagram-generator` dependencies.
3. After this you should already able to run this package. See README file for further information.

my references:
- https://stackoverflow.com/a/13500676/2496217

**Comment by seek-x2y** [comment]
+1 to PHP 8 support.

**Comment by allanlaal** [comment]
so current replacement for THIS is: 

https://github.com/laravel-shift/laravel-er-diagram-generator/tree/l9-compatibility
